#!/bin/zsh

ssh-history() {
  cat "$HISTFILE" | grep -E "^ssh\s" | sed -e 's/\s*$//' | sort | uniq -c | sort -nr | sed -e "s/^\s*[0-9]*\s//"
}

ssh-connect() {
  option=$(ssh-history | tr '\n' '|')
  listbox -t "Connect:" -o "$option" -r res
  echo ""
  echo $res >> $HISTFILE
  eval $res
}
